services:
  db:
    image: postgres:16
    container_name: task_manager_db
    environment:
      POSTGRES_USER: taskmanager
      POSTGRES_PASSWORD: taskmanager1234
      POSTGRES_DB: taskmanager
    ports:
      - "5432:5432"
    volumes:
      - taskmanager_pg:/var/lib/postgresql/data

volumes:
  taskmanager_pg:
